Working on workflow - Sat Jul 15 03:57:11 AM UTC 2023

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -46,35 +46,16 @@ jobs:
         fi
         echo -e "$cppproj_debian_md5_text" > "${rootpath}/docs/json/cppproj_debian_md5.json" || exit 115
         sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum ${rootpath}/debian/cppproj-1.0.0.deb | cut -d' ' -f 1)\"/g" "${rootpath}/docs/json/cppproj_debian_md5.json" || exit 114
-        echo -e "=========================\n========================="
-        ls "${rootpath}/docs/json" || exit 255
-        cat "${rootpath}/docs/json/cppproj_debian_md5.json" || exit 254
-        echo -e "=========================\n========================="
-        echo "Planned failure - [253]"
-        exit 253
-        sudo apt update  || exit 121
-        sudo apt install g++-arm-linux-gnueabihf g++-aarch64-linux-gnu -y  || exit 120
-        cd "${rootpath}/linux"
-        make android32staticall || exit 119
-        cppproj_arm32_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "lspids.arm32 MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "android"\n}'
-        if ! [[ -f "${rootpath}/docs/json/cppproj_arm32_md5.json" ]]; then
-          touch "${rootpath}/docs/json/cppproj_arm32_md5.json"
-        fi
-        echo -e "$cppproj_arm32_md5_text" > "${rootpath}/docs/json/cppproj_arm32_md5.json"
-        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum ${rootpath}/linux/android/static/32/lspids.arm32 | cut -d' ' -f 1)\"/g" "${rootpath}/docs/json/cppproj_arm32_md5.json"
-        make android64staticall || exit 118
-        cppproj_aarch64_md5_text='{\n\t"schemaVersion": 1,\n\t"color": "2E9778",\n\t"label": "lspids.aarch64 MD5",\n\t"message": "PLACEHOLDER",\n\t"labelColor": "1d1d1d",\n\t"style": "for-the-badge",\n\t"namedLogo": "android"\n}'
-        if ! [[ -f "${rootpath}/docs/json/cppproj_aarch64_md5.json" ]]; then
-          touch "${rootpath}/docs/json/cppproj_aarch64_md5.json"
-        fi
-        echo -e "$cppproj_aarch64_md5_text" > "${rootpath}/docs/json/cppproj_aarch64_md5.json"
-        sed -i "s/\"message\": \".*\"/\"message\": \"$(md5sum ${rootpath}/linux/android/static/64/lspids.aarch64 | cut -d' ' -f 1)\"/g" "${rootpath}/docs/json/cppproj_aarch64_md5.json"
         cd "${rootpath}"
-        git add ${rootpath}/docs/json/*
-        git config --global user.name 'Lateralus138'
-        git config --global user.email 'Lateralus138@users.noreply.github.com'
-        git commit --allow-empty -am "Pushed $(printf '%s ' ${rootpath}/docs/json/*) to master. - $(date -u)"
-        git push --force origin master
+        git add ${rootpath}/docs/json/* || exit 113
+        git config --global user.name 'Lateralus138' || exit 112
+        git config --global user.email 'Lateralus138@users.noreply.github.com' || exit 111
+        git commit --allow-empty -am "Pushed $(printf '%s ' ${rootpath}/docs/json/*) to master. - $(date -u)" || exit 110
+        git push --force origin master || exit 109
+        echo -e "=========================\n========================="
+        echo -e "=========================\n========================="
+        echo "Planned failure - [255]"
+        exit 255
     - uses: ncipollo/release-action@v1
       with:
         allowUpdates: True
